apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kwetter
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kwetter
    spec:
      containers:
      - name: kwetter
        image: eu.gcr.io/kwetter-274507/IMAGE:TAG
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m  
