name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Build Docker image
        run: |-
          docker build --tag "eu.gcr.io/kwetter-274507/kwetter:latest"  ./
      - name: Authenticate into Google Cloud Platform
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: kwetter-274507

      - name: Configure Docker to use Google Cloud Platform
        run: "gcloud auth configure-docker --quiet"
      - run: |-
            gcloud container clusters  get-credentials ${{ secrets.GCLOUD_CLUSTER }} --zone ${{ secrets.GCLOUD_ZONE }}
            
      - name: Push image to Google Cloud Container Registry
        run: "docker push eu.gcr.io/kwetter-274507/kwetter:latest"
     
     
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      - name: Deploy 
        run: |-
          ./kustomize edit set image eu.gcr.io/kwetter-274507/IMAGE:TAG=eu.gcr.io/kwetter-274507/kwetter:latest
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/kwetter:latest
          kubectl get services -o wide
